config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :reviews, only: [:index, :show, :edit, :update]
  resources :user_bottles, only: [:index, :create, :new] do
    member do
      patch "/update_quantity", to: "user_bottles#update_quantity"
      # patch "/user_bottles/:id/update_quantity", to: "user_bottles#update_quantity"
    end
  end

  resources :wishes, only: [:index, :destroy]
  resources :bottles, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
    resources :wishes, only: [:new, :create]
  end
  resources :recommendations, only: [:index]
  get 'recommendations/search', to: "recommendations#search", as: :search
  get 'pages/home', to: "pages#home", as: :home
end

app/models/wish.rb
class Wish < ApplicationRecord
  belongs_to :bottle
  belongs_to :user
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
 before_action :set_wish, only: [:edit, :update, :destroy]
  def index
    @wishes = current_user.wishes
    @user_bottle = UserBottle.new
  end

  def new
    @wish = Wish.new
  end

  def create
    @wish = Wish.new
    @bottle = Bottle.find(params[:bottle_id])
    @wish.bottle = @bottle
    @wish.user = current_user

    if @wish.save!
      respond_to do |format|
        format.html { redirect_to wishes_path }
        format.js  # <-- will render `app/views/wishes/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { redirect_to wishes_path }
        format.js  # <-- idem
      end
    end
  end

  def destroy
    @wish.destroy

    respond_to do |format|
      format.html { redirect_to wishes_path }
      format.js  # <-- will render `app/views/wishes/destroy.js.erb`
    end
  end

  private

  def set_wish
    @wish = current_user.wishes.find(params[:id])
  end
end

app/views/wishes/_card_wishlist.erb
<div class="piquette-wrapper" data-wish-id="<%= wish.id %>">
  <div class="piquette-card">

  <div id="bottle-wish-heart-<%= wish.bottle.id %>" class="bottle_wish_heart">
    <%= render "wishes/heart_button", bottle: wish.bottle %>
  </div>

    <div class="piquette-card-title">
      <h3><%= wish.bottle.title.capitalize %> <%= wish.bottle.year %></h3>
      <h4><%= wish.bottle.winery.name.upcase%></h4>
      <p><%= wish.bottle.region.name%></p>
    </div>

    <div class="piquette-card-content">

      <div class="piquette-card-content-item">
        <p><strong>Couleur</strong></p>
        <div class="piquette-card-content-item-color <%= wish.bottle.color.name %>"></div>
      </div>

      <div class="piquette-modal-content-item">
        <p><strong>Apogée</strong></p>
        <p><%= wish.bottle.best_after %></p>
        <p><%= wish.bottle.best_before %></p>
      </div>

      <div class="piquette-card-content-item">
        <p><strong>Maturation</strong></p>
        <% if wish.bottle.best_after <= Date.today.year && wish.bottle.best_before > Date.today.year %>
          <h5>👍</h5>
        <% elsif wish.bottle.best_before < Date.today.year %>
          <h5>👎</h5>
        <% elsif wish.bottle.best_after > Date.today.year %>
          <h5>✋</h5>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/wishes/_heart_button.html.erb
<% wish = current_user.wishes.find_by(bottle: bottle) %>
<% if wish %>
  <%= link_to wish_path(wish), method: :delete, remote: true do %>
    <span><i class="fas fa-heart active"></i></span>
  <% end %>
<% else %>
  <%= link_to bottle_wishes_path(bottle), method: :post, remote: true do %>
    <i class="fas fa-heart"></i>
  <% end %>
<% end %>

app/views/wishes/_modal_wishlist.erb
<div class="modal bottle-modal slide-in-fwd-center" id="modal<%= wish.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="false">
  <div type="button" class="close modal-close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </div>

  <div class="modal-dialog" role="document">
    <div class="modal-content bottle-modal-content">
      <div class="bottle-modal-header"></div>
      <div class="modal-body">
        <div class="piquette-card-title">
          <h3><%= wish.bottle.title.capitalize %> <%= wish.bottle.year %></h3>
          <h4><%= wish.bottle.winery.name.upcase%></h4>
          <p><%= wish.bottle.region.name%></p>
        </div>

        <div class="piquette-card-content">

          <div class="piquette-modal-content-item">
            <p><strong>Couleur</strong></p>
            <div class="piquette-card-content-item-color <%= wish.bottle.color.name %>"></div>
          </div>

          <div class="piquette-modal-content-item">
            <p><strong>Apogée</strong></p>
            <p><%= wish.bottle.best_after %></p>
            <p><%= wish.bottle.best_before %></p>
          </div>

          <div class="piquette-modal-content-item">
            <p><strong>Contenance</strong></p>
            <p>75cl</p>
          </div>

        </div>

        <% if wish.bottle.grapes %>
          <div class="piquette-modal-content">
            <p><strong>Cépages</strong></p>
            <p><%= wish.bottle.grapes %></p>
          </div>
        <% end %>

        <div class="piquette-modal-advice">
          <% if wish.bottle.tasting_advice %>
            <div class="piquette-modal-content">
              <p><strong>Conseils de dégustation</strong></p>
              <p><%= wish.bottle.tasting_advice %></p>
            </div>
          <% end %>

          <% if wish.bottle.wine_pairing %>
            <div class="piquette-modal-content">
              <p><strong>Accords mets-vins</strong></p>
              <p><%= wish.bottle.wine_pairing %></p>
            </div>
          <% end %>
        </div>

      </div>
    </div>

    <div class="wish-quantity-container">
      <div class="modal-content wish-modal-content">
        <%= simple_form_for @user_bottle do |f| %>
          <div>
            <%= f.hidden_field :bottle_id, value: wish.bottle_id %>
            <%= f.input :quantity, collection: 1..20, placeholder:0, label:"quantité" %>
          </div>

          <div>
            <%= f.button :submit, 'Ajouter à ma cave', class: "review-cta bloup review-cta-a" %>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/wishes/create.js.erb
function refreshHeartButton() {
  const heartButton = document.getElementById('bottle-wish-heart-<%= @wish.bottle.id %>');
  const innerHTML = '<%= j render "wishes/heart_button", bottle: @wish.bottle %>';
  heartButton.innerHTML = innerHTML;
}

refreshHeartButton();

app/views/wishes/destroy.js.erb
function refreshHeartButton() {
  const heartButton = document.getElementById('bottle-wish-heart-<%= @wish.bottle.id %>');
  const innerHTML = '<%= j render "wishes/heart_button", bottle: @wish.bottle %>';
  heartButton.innerHTML = innerHTML;
  document.querySelector("[data-wish-id='<%= @wish.id %>']").remove();
}

refreshHeartButton();

app/views/wishes/index.html.erb
<div class="piquette-header">
  <%= image_tag "wine.svg", alt: "ma wishlist", class: 'bottle-icon-2' %><h1>Ma wishlist</h1>
</div>

<div class="container_user_bottle_index">
  <% @wishes.each do |wish| %>
    <div type="button" data-toggle="modal" class="clickable" data-target="#modal<%= wish.id %>">
      <%= render "wishes/card_wishlist", wish: wish %>
    </div>
    <%= render "wishes/modal_wishlist", wish: wish %>
  <% end %>
</div>