config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :reviews, only: [:index, :show, :edit, :update]
  resources :user_bottles, only: [:index, :create, :new] do
    member do
      patch "/update_quantity", to: "user_bottles#update_quantity"
      # patch "/user_bottles/:id/update_quantity", to: "user_bottles#update_quantity"
    end
  end

  resources :wishes, only: [:index, :destroy]
  resources :bottles, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
    resources :wishes, only: [:new, :create]
  end
  resources :recommendations, only: [:index]
  get 'recommendations/search', to: "recommendations#search", as: :search
  get 'pages/home', to: "pages#home", as: :home
end

app/views/shared/_blur.html.erb
<div id="blur"></div>

app/views/shared/_custom_background.html.erb
<div class="custom-background">
  <div class="right-background">
  </div>
  <div class="bottom-background">
  </div>
  <div class="top-background">
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

<nav class="menu">
  <input type="checkbox" href="#" class="menu-open" name="menu-open" id="menu-open"/>
  <label class="menu-open-button" for="menu-open">
    <%= image_tag('grape', class:'nav-logo') %>
  </label>

  <%= link_to home_path, class:"menu-item" do %>
    <i class="fas fa-home"></i>
  <% end %>
  <%= link_to user_bottles_path, class:"menu-item" do %>
    <i class="fas fa-wine-glass-alt"></i>
  <% end %>
  <%= link_to reviews_path, class:"menu-item" do %>
    <i class="fas fa-book"></i>
  <% end %>
  <%= link_to wishes_path, class:"menu-item" do %>
    <i class="fas fa-heart"></i>
  <% end %>
  <a href="#" class="menu-item"> <i class="fas fa-user"></i> </a>

</nav>


<!-- filters -->
<!-- <svg xmlns="http://www.w3.org/2000/svg" version="1.1">
    <defs>
      <filter id="shadowed-goo">

          <feGaussianBlur in="SourceGraphic" result="blur" stdDeviation="10" />
          <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7" result="goo" />
          <feGaussianBlur in="goo" stdDeviation="3" result="shadow" />
          <feColorMatrix in="shadow" mode="matrix" values="0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 1 -0.2" result="shadow" />
          <feOffset in="shadow" dx="1" dy="1" result="shadow" />
          <feBlend in2="shadow" in="goo" result="goo" />
          <feBlend in2="goo" in="SourceGraphic" result="mix" />
      </filter>
      <filter id="goo">
          <feGaussianBlur in="SourceGraphic" result="blur" stdDeviation="10" />
          <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7" result="goo" />
          <feBlend in2="goo" in="SourceGraphic" result="mix" />
      </filter>
    </defs>
</svg> -->