config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :reviews, only: [:index, :show, :edit, :update]
  resources :user_bottles, only: [:index, :create, :new] do
    member do
      patch "/update_quantity", to: "user_bottles#update_quantity"
      # patch "/user_bottles/:id/update_quantity", to: "user_bottles#update_quantity"
    end
  end

  resources :wishes, only: [:index, :destroy]
  resources :bottles, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
    resources :wishes, only: [:new, :create]
  end
  resources :recommendations, only: [:index]
  get 'recommendations/search', to: "recommendations#search", as: :search
  get 'pages/home', to: "pages#home", as: :home
end

app/models/user_bottle.rb
class UserBottle < ApplicationRecord
  belongs_to :bottle
  belongs_to :user

  validates :quantity, presence: true

end

app/controllers/user_bottles_controller.rb
class UserBottlesController < ApplicationController
  def index
    if params[:query].present?
      if !params[:color].present?
        @region = Region.where("name ILIKE ?", "%#{params[:query]}%").first
        @user_bottles_list = Bottle.of_user(current_user).where(region_id: @region.id)
      else
        if params[:color] == 'rouge'
          @user_bottles_list = Bottle.of_user(current_user).color('Rouge').where(region_id: @region.id)
        elsif params[:color] == 'blanc'
          @user_bottles_list = Bottle.of_user(current_user).color('Blanc').where(region_id: @region.id)
        elsif params[:color] == "rose"
          @user_bottles_list = Bottle.of_user(current_user).color('Rosé').where(region_id: @region.id)
        end
      end
    elsif params[:color].present?
      if params[:color] == 'rouge'
        @user_bottles_list = Bottle.of_user(current_user).color('Rouge')
      elsif params[:color] == 'blanc'
        @user_bottles_list = Bottle.of_user(current_user).color('Blanc')
      elsif params[:color] == "rose"
        @user_bottles_list = Bottle.of_user(current_user).color('Rosé')
      end
    else
      @user_bottles_list = Bottle.of_user(current_user)
    end

    @user_bottle = UserBottle.new
  end

  def new
  end

  def create
    if UserBottle.where(bottle_id: params[:user_bottle][:bottle_id]).first
      update_quantity
    else
      @user_bottle = UserBottle.new(
        bottle_id: params[:user_bottle][:bottle_id],
        quantity: params[:user_bottle][:quantity]
      )
      # raise
      @user_bottle.user = current_user
      @user_bottle.save
      redirect_to user_bottles_path
    end
  end

  def update_quantity
    if params[:addition_type]
      p params
      @user_bottle = UserBottle.find(params[:id])
      @user_bottle.quantity += params[:addition_type] == "plus" ? 1 : -1
      p @user_bottle
      # binding.pry
      if @user_bottle.save
        respond_to do |format|
          format.html { redirect_to user_bottles_path }
          format.js
        end
      else
        respond_to do |format|
          format.html { render 'user_bottle/index' }
          format.js
        end
      end
    else
      @user_bottle = UserBottle.where(bottle_id: params[:user_bottle][:bottle_id]).first
      @user_bottle.quantity += params[:user_bottle][:quantity].to_i
      if @user_bottle.save!
        redirect_to user_bottles_path
      end
    end
  end

  private

  def set_user_bottles
    @user_bottle = current_user.user_bottles.find(params[:id])
  end
end

app/views/user_bottles/_card.html.erb
<div class="piquette-wrapper">

  <div class="piquette-card">

    <div class="piquette-card-title">
      <h3><%= user_bottle.title.capitalize %> <%= user_bottle.year %></h3>
      <h4><%= user_bottle.winery.name.upcase%></h4>
      <p><%= user_bottle.region.name%></p>
    </div>

    <div class="piquette-card-content">

      <div class="piquette-card-content-item">
        <p><strong>Couleur</strong></p>
        <div class="piquette-card-content-item-color <%= user_bottle.color.name %>"></div>
      </div>

      <div class="piquette-card-content-item">
        <p><strong>Quantité</strong></p>
        <h5><%= UserBottle.find_by(bottle_id: user_bottle.id).quantity %></h5>
      </div>

      <div class="piquette-card-content-item">
        <p><strong>Maturation</strong></p>
        <% if user_bottle.best_after <= Date.today.year && user_bottle.best_before > Date.today.year %>
          <h5>👍</h5>
        <% elsif user_bottle.best_before < Date.today.year %>
          <h5>👎</h5>
        <% elsif user_bottle.best_after > Date.today.year %>
          <h5>✋</h5>
        <% end %>
      </div>

    </div>

  </div>

</div>

app/views/user_bottles/_modal.html.erb
<div class="modal bottle-modal slide-in-fwd-center" id="modal<%= user_bottle.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="false">
  <div type="button" class="close modal-close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </div>

  <div class="modal-dialog" role="document">


    <div class="modal-content bottle-modal-content" id="usr-modal">
      <div class="bottle-modal-header">
      </div>
        <div class="modal-body">

          <div class="piquette-card-title">
            <h3><%= user_bottle.title.capitalize %> <%= user_bottle.year %></h3>
            <h4><%= user_bottle.winery.name.upcase%></h4>
            <p><%= user_bottle.region.name%></p>
          </div>

          <div class="piquette-card-content">

            <div class="piquette-modal-content-item">
              <p><strong>Couleur</strong></p>
              <div class="piquette-card-content-item-color <%= user_bottle.color.name %>"></div>
            </div>

            <div class="piquette-modal-content-item">
              <p><strong>Apogée</strong></p>
              <p><%= user_bottle.best_after %></p>
              <p><%= user_bottle.best_before %></p>
            </div>

            <div class="piquette-modal-content-item">
              <p><strong>Contenance</strong></p>
              <p>75cl</p>
            </div>

          </div>

          <div class="piquette-modal-advice">

            <% if user_bottle.grapes %>
              <div class="piquette-modal-content">
                <p><strong>Cépages</strong></p>
                <p><%= user_bottle.grapes %></p>
              </div>
            <% end %>

            <% if user_bottle.tasting_advice %>
              <div class="piquette-modal-content">
                <p><strong>Conseils de dégustation</strong></p>
                <p><%= user_bottle.tasting_advice %></p>
              </div>
            <% end %>

            <% if user_bottle.wine_pairing %>
              <div class="piquette-modal-content">
                <p><strong>Accords mets-vins</strong></p>
                <p><%= user_bottle.wine_pairing %></p>
              </div>
            <% end %>

          </div>

          <div class="piquette-modal-quantity">
            <div class="piquette-modal-title-quantity">
              <p><strong>Quantité</strong></p>
            </div>

            <div class="piquette-modal-content-quantity">
              <%= link_to update_quantity_user_bottle_path(UserBottle.find_by(bottle_id: user_bottle.id), addition_type: "minus"), method: :patch, id:'btn-minus', remote: true do %>
                <i class="fas fa-minus-circle" id='btn-minus'></i>
              <% end %>

              <h5 id="bottle-quantity_<%= user_bottle.id %>"><%= UserBottle.find_by(bottle_id: user_bottle.id).quantity %></h5>

              <%= link_to update_quantity_user_bottle_path(UserBottle.find_by(bottle_id: user_bottle.id), addition_type: "plus"), method: :patch, id:'btn-minus', remote: true do %>
               <i class="fas fa-plus-circle" id='btn-plus'></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="bottle-modal-cta bloup">
        <%= link_to new_bottle_review_path(user_bottle) do %>
          <div>Ajouter mon avis</div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/user_bottles/_search_bar.html.erb
<div  id="search-btn">
  <i class="fas fa-search" style="font-size: 30px; color: white"></i>
  <br>
</div>
<div class="search-group">
  <div class="search-bar hidden-search">
    <div class='search-field'>
      <%= form_tag user_bottles_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Région ?"
        %>
      <% end %>
    </div>

    <div class='filters'>
      <% if params[:color] == 'rouge' %>
        <%= link_to user_bottles_path do %>
          <div class='search-btn' id='all'></div>
        <% end %>
        <%= link_to user_bottles_path(color: "rouge") do %>
          <div class='search-btn active' id='rouge-btn'></div>
        <% end %>
        <%= link_to user_bottles_path(color: "blanc") do %>
          <div class='search-btn' id='blanc-btn'></div>
        <% end %>
        <%= link_to user_bottles_path(color: "rose") do %>
          <div class='search-btn' id='rose-btn'></div>
        <% end %>
      <% elsif params[:color] == 'blanc' %>
        <%= link_to user_bottles_path do %>
          <div class='search-btn' id='all'></div>
        <% end %>
        <%= link_to user_bottles_path(color: "rouge") do %>
          <div class='search-btn' id='rouge-btn'></div>
        <% end %>
        <%= link_to user_bottles_path(color: "blanc") do %>
          <div class='search-btn active' id='blanc-btn'></div>
        <% end %>
        <%= link_to user_bottles_path(color: "rose") do %>
          <div class='search-btn' id='rose-btn'></div>
        <% end %>
      <% elsif params[:color] == 'rose' %>
        <%= link_to user_bottles_path do %>
          <div class='search-btn' id='all'></div>
        <% end %>
        <%= link_to user_bottles_path(color: "rouge") do %>
          <div class='search-btn' id='rouge-btn'></div>
        <% end %>
        <%= link_to user_bottles_path(color: "blanc") do %>
          <div class='search-btn' id='blanc-btn'></div>
        <% end %>
        <%= link_to user_bottles_path(color: "rose") do %>
          <div class='search-btn active' id='rose-btn'></div>
        <% end %>
      <% else %>
        <%= link_to user_bottles_path do %>
          <div class='search-btn' id='all'></div>
        <% end %>
        <%= link_to user_bottles_path(color: "rouge") do %>
          <div class='search-btn' id='rouge-btn'></div>
        <% end %>
        <%= link_to user_bottles_path(color: "blanc") do %>
          <div class='search-btn' id='blanc-btn'></div>
        <% end %>
        <%= link_to user_bottles_path(color: "rose") do %>
          <div class='search-btn' id='rose-btn'></div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/user_bottles/index.html.erb
<div class="piquette-header">

  <%= image_tag "wine.svg", alt: "ma cave", class: 'bottle-icon-2' %><h1>Ma cave</h1>

</div>


<%= render 'user_bottles/search_bar' %>

<div class="container_user_bottle_index">
  <% @user_bottles_list.order(:title).each do |user_bottle| %>
    <% if UserBottle.find_by(bottle_id: user_bottle.id).quantity > 0 %>
      <div type="button" data-toggle="modal" class="clickable" data-target="#modal<%= user_bottle.id %>">
        <%= render "user_bottles/card", user_bottle: user_bottle %>
      </div>
      <%= render "user_bottles/modal", user_bottle: user_bottle %>
    <% end %>
  <% end %>
</div>

app/views/user_bottles/update_quantity.js.erb
document.getElementById('bottle-quantity_<%= @user_bottle.bottle_id %>').innerText = "<%= @user_bottle.quantity %>";